name: nonlinear-deformation-design
channels:
  - conda-forge
dependencies:
  - conda-forge::pip=21.2.4
  - conda-forge::python=3.9.12
  - pip:
    - autopep8==1.6.0
    - matplotlib==3.8.4
    - numpy==1.24.0
    - pandas==1.5.3
    - pylint==2.12.2
    - scikit-learn==1.2.2
    - scipy==1.7.3
    - torch==2.2.2
